### ISSUE TITLE
Remove 'system.' prefix when interacting with ArsPushTarget resources

### ISSUE THREAD

**Issue by mjswan** [Vantiq/vantiq-sdk-ios#3]
Changes in the 1.35 server make the 'system.' prefix illegal, resulting in an HTTP 500 REST error.

**Comment by sfitts** [comment]
Do we have the same issue with the Android client?

@rblumer4 is testing the mobile clients part of our standard release process?  Trying to understand how this one slipped through.  The change itself was made fairly early in the cycle IIRC (it was actually a bug fix, closing a hole that should have been closed ages ago).

**Comment by steve-langley** [comment]
No, this seems to work on Android. I don't use "system." with ArsPushTarget.

**Comment by rblumer4** [comment]
> @rblumer4 is testing the mobile clients part of our standard release process?

Yes, I ran our basic Mobile Client tests against staging using iOS, and @skyler1ackerman ran them against staging using Android.
They are here:  https://github.com/Vantiq/iqtools/tree/master/test/test_data/mobile_clients

Note that I didn't rebuild the clients or the collaborations that the tests use--I just re-used some imported during1.34.   Though I had to change at least one of them for 1.35.

@mjswan,  let us know what steps to add to those tests so that we would catch this problem...

**Comment by mjswan** [comment]
> @mjswan, let us know what steps to add to those tests so that we would catch this problem...

The tests you ran are focused on testing Client functionality. I suggest adding at least logging out of an existing account and logging in to the same account. This forces a reregistration of the APNS token to the ArsPushTarget resource and other important mechanics of authentication.

**Comment by mjswan** [comment]
Fixed in version 3.6.0 of the iOS app.
